// Android-native compile/link seam for the exact Cocos image decoder closure.
// Runtime execution requires an Android device (or emulator); this target is
// EXCLUDE_FROM_ALL so the ordinary engine build remains unchanged.

#include "platform/CCImage.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>

namespace {

constexpr unsigned char kRgbaPng[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
    0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,0x08,0x06,0x00,0x00,0x00,0x1f,0x15,0xc4,
    0x89,0x00,0x00,0x00,0x0d,0x49,0x44,0x41,0x54,0x78,0x9c,0x63,0xf8,0xcf,0xc0,0xf0,
    0x1f,0x00,0x05,0x00,0x01,0xff,0x89,0x99,0x3d,0x1d,0x00,0x00,0x00,0x00,0x49,0x45,
    0x4e,0x44,0xae,0x42,0x60,0x82,
};

// Palette PNG with no tRNS chunk. The decoder must add opaque alpha after
// expanding the palette to RGB.
constexpr unsigned char kPalettePng[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
    0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,0x08,0x03,0x00,0x00,0x00,0x28,0xcb,0x34,
    0xbb,0x00,0x00,0x00,0x03,0x50,0x4c,0x54,0x45,0x00,0xff,0x00,0x34,0x5e,0xc0,0xa8,
    0x00,0x00,0x00,0x0a,0x49,0x44,0x41,0x54,0x78,0x9c,0x63,0x60,0x00,0x00,0x00,0x02,
    0x00,0x01,0x48,0xaf,0xa4,0x71,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,0x44,0xae,0x42,
    0x60,0x82,
};

// A valid 1x1 JPEG generated by Pillow. Keeping it as base64 makes this
// single-source seam reviewable without adding a binary fixture to the repo.
constexpr char kJpegBase64[] =
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/"
    "2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAABAAEDAREAAhEBAxEB/"
    "8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/"
    "8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD50r8MP9Uz/9k=";

constexpr unsigned char kOversizedPng[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
    0x00,0x00,0x40,0x01,0x00,0x00,0x00,0x01,0x08,0x06,0x00,0x00,0x00,0xc9,0x5d,0xdd,
    0x66,0x00,0x00,0x00,0x09,0x49,0x44,0x41,0x54,0x78,0x9c,0x63,0x00,0x00,0x00,0x01,
    0x00,0x01,0x5e,0xff,0x7d,0xf9,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,0x44,0xae,0x42,
    0x60,0x82,
};

int base64_value(char value)
{
    if (value >= 'A' && value <= 'Z') return value - 'A';
    if (value >= 'a' && value <= 'z') return value - 'a' + 26;
    if (value >= '0' && value <= '9') return value - '0' + 52;
    if (value == '+') return 62;
    if (value == '/') return 63;
    return -1;
}

size_t decode_base64(const char* encoded, unsigned char* output, size_t capacity)
{
    size_t output_size = 0U;
    std::uint32_t accumulator = 0U;
    unsigned int bits = 0U;
    for (size_t index = 0U; encoded[index] != '\0'; ++index)
    {
        if (encoded[index] == '=')
            break;
        const int value = base64_value(encoded[index]);
        if (value < 0)
            return 0U;
        accumulator = (accumulator << 6U) | static_cast<std::uint32_t>(value);
        bits += 6U;
        if (bits >= 8U)
        {
            bits -= 8U;
            if (output_size >= capacity)
                return 0U;
            output[output_size++] = static_cast<unsigned char>((accumulator >> bits) & 0xffU);
            accumulator = bits == 0U ? 0U : accumulator & ((1U << bits) - 1U);
        }
    }
    return output_size;
}

bool expect(bool condition, const char* message)
{
    if (!condition)
        std::fprintf(stderr, "Cocos image seam failure: %s\n", message);
    return condition;
}

bool state_unchanged(cocos2d::Image& image, unsigned char* data, ssize_t length,
                     int width, int height, cocos2d::Image::Format format)
{
    return image.getData() == data && image.getDataLen() == length &&
           image.getWidth() == width && image.getHeight() == height &&
           image.getFileType() == format;
}

}  // namespace

int main()
{
    cocos2d::Image rgba;
    if (!expect(rgba.initWithImageData(kRgbaPng, sizeof(kRgbaPng)), "RGBA PNG decode") ||
        !expect(rgba.getWidth() == 1 && rgba.getHeight() == 1, "RGBA dimensions") ||
        !expect(rgba.getDataLen() == 4, "RGBA decoded length") ||
        !expect(rgba.getData()[0] == 0xff && rgba.getData()[1] == 0x00 &&
                    rgba.getData()[2] == 0x00 && rgba.getData()[3] == 0xff,
                "RGBA pixel") ||
        !expect(rgba.getRenderFormat() == cocos2d::Texture2D::PixelFormat::RGBA8888,
                "RGBA render format"))
        return 1;

    cocos2d::Image palette;
    if (!expect(palette.initWithImageData(kPalettePng, sizeof(kPalettePng)),
                "palette PNG without tRNS decode") ||
        !expect(palette.getDataLen() == 4 && palette.getData()[0] == 0x00 &&
                    palette.getData()[1] == 0xff && palette.getData()[2] == 0x00 &&
                    palette.getData()[3] == 0xff,
                "palette opaque RGBA pixel"))
        return 1;

    std::array<unsigned char, 700> jpeg_bytes{};
    const size_t jpeg_size = decode_base64(kJpegBase64, jpeg_bytes.data(), jpeg_bytes.size());
    if (!expect(jpeg_size >= 2U && jpeg_bytes[0] == 0xff &&
                    jpeg_bytes[jpeg_size - 2U] == 0xff &&
                    jpeg_bytes[jpeg_size - 1U] == 0xd9,
                "JPEG fixture decode"))
        return 1;
    cocos2d::Image jpeg;
    if (!expect(jpeg.initWithImageData(jpeg_bytes.data(), static_cast<ssize_t>(jpeg_size)),
                "JPEG decode") ||
        !expect(jpeg.getWidth() == 1 && jpeg.getHeight() == 1, "JPEG dimensions") ||
        !expect(jpeg.getDataLen() == 4, "JPEG decoded length") ||
        !expect(jpeg.getData()[3] == 0xff, "JPEG alpha filler"))
        return 1;

    unsigned char* previous_data = rgba.getData();
    const ssize_t previous_length = rgba.getDataLen();
    const int previous_width = rgba.getWidth();
    const int previous_height = rgba.getHeight();
    const cocos2d::Image::Format previous_format = rgba.getFileType();
    if (!expect(!rgba.initWithImageData(kRgbaPng, sizeof(kRgbaPng) - 3U),
                "truncated PNG rejection") ||
        !expect(state_unchanged(rgba, previous_data, previous_length, previous_width,
                                 previous_height, previous_format),
                "PNG failure preserves state"))
        return 1;
    if (!expect(!rgba.initWithImageData(jpeg_bytes.data(), 12), "truncated JPEG rejection") ||
        !expect(state_unchanged(rgba, previous_data, previous_length, previous_width,
                                 previous_height, previous_format),
                "JPEG failure preserves state"))
        return 1;

    unsigned char raw_pixel[4] = {0xff, 0x00, 0x00, 0xff};
    if (!expect(!rgba.initWithRawData(raw_pixel, sizeof(raw_pixel), 16384, 16384, 8),
                "raw decoded byte ceiling") ||
        !expect(!rgba.initWithImageData(kOversizedPng, sizeof(kOversizedPng)),
                "PNG dimension ceiling"))
        return 1;

    // Exercise repeated longjmp/cleanup paths; this is intentionally bounded
    // and remains a compile/link seam until an Android runner is available.
    for (size_t length = 0U; length < sizeof(kRgbaPng); ++length)
        (void)rgba.initWithImageData(kRgbaPng, static_cast<ssize_t>(length));
    for (size_t length = 0U; length < 64U; ++length)
        (void)jpeg.initWithImageData(jpeg_bytes.data(), static_cast<ssize_t>(length));
    return 0;
}
