#!/usr/bin/env python3
"""Generate or verify the file-level checksums of vendored source snapshots."""

from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path, PurePosixPath


MANIFEST_PATH = Path("third_party/source_files.sha256")
SOURCES_PATH = Path("third_party/sources.toml")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def source_destinations(root: Path) -> dict[str, Path]:
    configuration = tomllib.loads((root / SOURCES_PATH).read_text(encoding="utf-8"))
    destinations: dict[str, Path] = {}
    for source in configuration.get("sources", []):
        source_id = source["id"]
        destination = (root / source["destination"]).resolve()
        if source_id in destinations:
            raise ValueError(f"duplicate source id: {source_id}")
        if not destination.is_relative_to(root):
            raise ValueError(f"source destination escapes repository: {destination}")
        destinations[source_id] = destination
    return destinations


def collect(root: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    for source_id, destination in source_destinations(root).items():
        if not destination.is_dir():
            raise FileNotFoundError(f"missing source snapshot: {destination}")
        for candidate in destination.rglob("*"):
            if candidate.is_symlink():
                raise ValueError(f"symbolic links are not allowed in snapshots: {candidate}")
            if not candidate.is_file():
                continue
            relative = candidate.relative_to(destination).as_posix()
            manifest_path = f"{source_id}/{relative}"
            entries[manifest_path] = sha256(candidate)
    return entries


def load_manifest(path: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw_line or raw_line.startswith("#"):
            continue
        try:
            digest, relative = raw_line.split("  ", 1)
        except ValueError as error:
            raise ValueError(f"invalid checksum line {line_number}") from error
        if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
            raise ValueError(f"invalid SHA-256 on line {line_number}")
        path = PurePosixPath(relative)
        if path.is_absolute() or ".." in path.parts:
            raise ValueError(f"unsafe path on line {line_number}: {relative}")
        if relative in entries:
            raise ValueError(f"duplicate path on line {line_number}: {relative}")
        entries[relative] = digest
    return entries


def write_manifest(path: Path, entries: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/verify_source_snapshots.py --generate.",
        "# Format: SHA-256, two spaces, source-id/path.",
    ]
    lines.extend(f"{digest}  {relative}" for relative, digest in sorted(entries.items()))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def verify(expected: dict[str, str], actual: dict[str, str]) -> list[str]:
    failures: list[str] = []
    for relative in sorted(expected.keys() - actual.keys()):
        failures.append(f"missing: {relative}")
    for relative in sorted(actual.keys() - expected.keys()):
        failures.append(f"unexpected: {relative}")
    for relative in sorted(expected.keys() & actual.keys()):
        if expected[relative] != actual[relative]:
            failures.append(f"checksum mismatch: {relative}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--generate",
        action="store_true",
        help="replace the checksum manifest with the current source snapshot hashes",
    )
    arguments = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    manifest_path = root / MANIFEST_PATH
    actual = collect(root)

    if arguments.generate:
        write_manifest(manifest_path, actual)
        print(f"Wrote {len(actual)} source file checksums to {manifest_path}.")
        return 0

    if not manifest_path.is_file():
        print(f"Missing checksum manifest: {manifest_path}", file=sys.stderr)
        return 1

    failures = verify(load_manifest(manifest_path), actual)
    if failures:
        print("Source snapshot verification failed:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1

    print(f"Source snapshot verification passed ({len(actual)} files checked).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
